name: Clean All Player Branches

on:
  workflow_dispatch:  # Esecuzione manuale
  schedule:
    - cron: '0 3 * * *'  # Esegui ogni giorno alle 3 AM (UTC)

jobs:
  clean_branches:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branches:
          - Player_S4me
          - Player_Mandrakodi
          - Player_Wltv
          - Player_Thegroove
          - Player_Torrent
          - Player_Scrubsv2
    steps:
      - name: Checkout branch (${{ matrix.branches }})
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branches }}
          fetch-depth: 0

      - name: Sync from main (mantieni struttura base)
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin main
          git merge origin/main --no-edit --allow-unrelated-histories || true

      - name: Pulizia selettiva (mantieni solo i file del player)
        run: |
          # Pattern diversi per ogni branch (personalizza questi grep)
          case "${{ matrix.branches }}" in
            *S4me*)
              KEEP_PATTERN="S4Me_player_|S4me_"
              ;;
            *Mandrakodi*)
              KEEP_PATTERN="MK_player_"
              ;;
            *Wltv*)
              KEEP_PATTERN="WLTV"
              ;;
            *Thegroove*)
              KEEP_PATTERN="TG360_player_"
              ;;
            *Torrent*)
              KEEP_PATTERN="elementum"
              ;;
            *Scrubsv2*)
              KEEP_PATTERN="direct"
              ;;
          esac

          # Elimina tutto tranne i file del player e la cartella .github
          find . -type f -name "*.json" | grep -vE "$KEEP_PATTERN" | xargs rm -f
          find . -type d -not -name ".github" -not -path "." | xargs rm -rf 2>/dev/null || true

          git add .
          git commit -m "🔄 Auto-clean: mantengo solo file $KEEP_PATTERN" --allow-empty || echo "Nessun cambiamento"
          git push origin ${{ matrix.branches }}

      - name: Force cleanup (opzionale, solo se necessario)
        if: always()  # Esegui anche se falliscono i passi precedenti
        run: |
          git add .
          git commit -m "🧹 Reset completo branch" --allow-empty
          git push origin ${{ matrix.branches }} --force
