name: Update All Player Branches

on:
  push:
    branches:
      - main

jobs:
  update_s4me_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout S4Me branch
        uses: actions/checkout@v4
        with:
          ref: Player_S4me
          fetch-depth: 0

      - name: Sync from main
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin main
          git merge origin/main --no-edit

      - name: Filter S4Me files
        run: |
          find . -type f -name "*.json" | grep -E "S4Me_player_|S4me_" > files_to_keep.txt
          find . -type f -name "*.json" | grep -vE "S4Me_player_|S4me_" | xargs rm -f
          cat files_to_keep.txt | xargs -I {} git add {}
          git commit -m "Auto-update S4Me player files from main" || echo "No changes to commit"
          git push origin Player_S4me

  update_mandrakodi_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Mandrakodi branch
        uses: actions/checkout@v4
        with:
          ref: Player_Mandrakodi
          fetch-depth: 0

      - name: Sync from main
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin main
          git merge origin/main --no-edit

      - name: Filter Mandrakodi files
        run: |
          find . -type f -name "*.json" | grep -E "MK_player_" > files_to_keep.txt
          find . -type f -name "*.json" | grep -vE "MK_player_" | xargs rm -f
          cat files_to_keep.txt | xargs -I {} git add {}
          git commit -m "Auto-update Mandrakodi player files from main" || echo "No changes to commit"
          git push origin Player_Mandrakodi

  update_wltv_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout WLTV branch
        uses: actions/checkout@v4
        with:
          ref: Player_Wltv
          fetch-depth: 0

      - name: Sync from main
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin main
          git merge origin/main --no-edit

      - name: Filter WLTV files
        run: |
          find . -type f -name "*.json" | grep -E "WLTV" > files_to_keep.txt
          find . -type f -name "*.json" | grep -vE "WLTV" | xargs rm -f
          cat files_to_keep.txt | xargs -I {} git add {}
          git commit -m "Auto-update WLTV player files from main" || echo "No changes to commit"
          git push origin Player_Wltv

  update_thegroove_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TheGroove branch
        uses: actions/checkout@v4
        with:
          ref: Player_Thegroove
          fetch-depth: 0

      - name: Sync from main
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin main
          git merge origin/main --no-edit

      - name: Filter TheGroove files
        run: |
          find . -type f -name "*.json" | grep -E "TG360_player_" > files_to_keep.txt
          find . -type f -name "*.json" | grep -vE "TG360_player_" | xargs rm -f
          cat files_to_keep.txt | xargs -I {} git add {}
          git commit -m "Auto-update TheGroove player files from main" || echo "No changes to commit"
          git push origin Player_Thegroove

  update_torrent_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Torrent branch
        uses: actions/checkout@v4
        with:
          ref: Player_Torrent
          fetch-depth: 0

      - name: Sync from main
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin main
          git merge origin/main --no-edit

      - name: Filter Torrent files
        run: |
          find . -type f -name "*.json" | grep -E "elementum" > files_to_keep.txt
          find . -type f -name "*.json" | grep -vE "elementum" | xargs rm -f
          cat files_to_keep.txt | xargs -I {} git add {}
          git commit -m "Auto-update Torrent player files from main" || echo "No changes to commit"
          git push origin Player_Torrent

  update_scrubsv2_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ScrubsV2 branch
        uses: actions/checkout@v4
        with:
          ref: Player_Scrubsv2
          fetch-depth: 0

      - name: Sync from main
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin main
          git merge origin/main --no-edit

      - name: Filter ScrubsV2 files
        run: |
          find . -type f -name "*.json" | grep -E "Scrubs" > files_to_keep.txt
          find . -type f -name "*.json" | grep -vE "Scrubs" | xargs rm -f
          cat files_to_keep.txt | xargs -I {} git add {}
          git commit -m "Auto-update ScrubsV2 player files from main" || echo "No changes to commit"
          git push origin Player_Scrubsv2
